In [1]:
import numpy as np

In [2]:
www = np.array([100.,200.,300.], dtype='float32')

In [3]:
ww2 = www + 0.1; ww2

array([ 100.09999847,  200.1000061 ,  300.1000061 ], dtype=float32)

In [4]:
ww2 - 0.1

array([ 100.,  200.,  300.], dtype=float32)

In [5]:
ww2 - 0.1

array([ 100.,  200.,  300.], dtype=float32)

In [11]:
def log(X):
    return np.log10(X + 1.0)
def unlog(X):
    return np.clip(np.power(10., X) - 1.0, 0.0, None)
def transform(data_ori, center, scale):
    return (data_ori - center) / scale
def untransform(data, center, scale):
    return data * scale + center
def smape(y_true, y_pred, axis=None):
    '''Symmetric mean absolute percentage error'''
    diff = np.abs((y_true - y_pred) / 
                  np.clip(np.abs(y_true) + np.abs(y_pred), 1e-07, None))
    return 200. * np.nanmean(diff, axis=axis)

In [12]:
logwww = log(www); logwww

array([ 2.00432134,  2.30319595,  2.47856641], dtype=float32)

In [13]:
www_tt = unlog(logwww); www_tt

array([  99.99999237,  199.99995422,  299.99993896], dtype=float32)

In [14]:
smape(www,www_tt)

1.695421332215119e-05

In [15]:
wwwmed = np.median(logwww); wwwmed

2.303196

In [16]:
wwwstd = np.std(logwww); wwwstd

0.19578594

In [17]:
www_s = transform(logwww, center=wwwmed, scale=wwwstd); www_s

array([-1.52653766,  0.        ,  0.89572549], dtype=float32)

In [18]:
www_ss = untransform(www_s, center=wwwmed, scale=wwwstd); www_ss

array([ 2.00432134,  2.30319595,  2.47856641], dtype=float32)

In [19]:
www_sst = unlog(www_ss); www_sst

array([  99.99999237,  199.99995422,  299.99993896], dtype=float32)

In [20]:
smape(www_sst,www)

1.695421332215119e-05

In [21]:
%whos

Variable      Type        Data/Info
-----------------------------------
log           function    <function log at 0x00000000061D3EA0>
logwww        ndarray     3: 3 elems, type `float32`, 12 bytes
np            module      <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
smape         function    <function smape at 0x00000000061D3D90>
transform     function    <function transform at 0x00000000061D3C80>
unlog         function    <function unlog at 0x00000000061D3730>
untransform   function    <function untransform at 0x00000000061D3D08>
ww2           ndarray     3: 3 elems, type `float32`, 12 bytes
www           ndarray     3: 3 elems, type `float32`, 12 bytes
www_s         ndarray     3: 3 elems, type `float32`, 12 bytes
www_ss        ndarray     3: 3 elems, type `float32`, 12 bytes
www_sst       ndarray     3: 3 elems, type `float32`, 12 bytes
www_tt        ndarray     3: 3 elems, type `float32`, 12 bytes
wwwmed        float32     2.3032
wwwstd        float32     0.195786
